### ISSUE TITLE
Interfacing 4x4 Matrix Keypad with Beaglebone Black Wireless

### ISSUE THREAD

**Issue by mikeshams** [chandrashekar1994/captson-project-summer-2020#4]

**Comment by manharjotkaur** [comment]
The code to interface a 4*4 matrix keypad with Beagle bone wireless is uploaded in C Language as keypad.c

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connecting the Keypad to the BBB in terms of Hardware or Software?
2. Did you try to use dts or dtb files? Why not?

**Comment by mikeshams** [comment]
**You need to fix bouncing issue!**

**Comment by manharjotkaur** [comment]
1. As we have keypad.h library for Arduino board, for BB to interface with keypad, it does not have a designated library as it does have for ultrasonic sensor.
There was debouncing effect for keys pressed, for each key pressed, multiple requests are sent, so a no. of times, it is getting printed on screen.
The proper pin connection is required to the rows and columns to get output on screen.

2. NO, we have not used ant dts and dtb files, we wrote the code in C language
dtb file needs a detailed knowledge of harware, it is  hard to figure out the exact syntax to use to express what we want to do(sometimes documentation is lacking) and it basically works on trial and error method.

**Comment by manharjotkaur** [comment]
We can solve the issue by connecting the Arduino as a slave device in between keypad and Beagle bone wireless i.e., the main microcontroller used. We were facing a debouncing issue in a matrix keypad directly connected to beagle bone . As beaglebone has very responsive GPIO pins and for matrix keypad we have 4 rows and 4 columns. So, for that we need very fast switching between GPIO  to read a 16 keys.
