### ISSUE TITLE
Interfacing Camera module with Beaglebone Black Wireless.

### ISSUE THREAD

**Issue by mikeshams** [chandrashekar1994/captson-project-summer-2020#7]

**Comment by mikeshams** [comment]
1. what issues did you or others might face with connection of a camera to a BBB in terms of hardware and software?
2. how did you resolve them?

**Comment by manharjotkaur** [comment]
1. When we try to capture the image from fswebcam, there was frame lagging in the photo captured  and the resolution was also poor.
2. So, we solved the problem by setting the resolution as it depends on the camera megapixels and we have used command for that like 
fswebcam -r 120x120
